/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/aceitarProposta`; params?: Router.UnknownInputParams; } | { pathname: `/agendar`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/confirmarContratacao`; params?: Router.UnknownInputParams; } | { pathname: `/contratante`; params?: Router.UnknownInputParams; } | { pathname: `/enviarProposta`; params?: Router.UnknownInputParams; } | { pathname: `/homeContratante`; params?: Router.UnknownInputParams; } | { pathname: `/homePrestador`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mensagens`; params?: Router.UnknownInputParams; } | { pathname: `/meusProjetos`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/perfilPrestador`; params?: Router.UnknownInputParams; } | { pathname: `/postarServico`; params?: Router.UnknownInputParams; } | { pathname: `/prestador`; params?: Router.UnknownInputParams; } | { pathname: `/resumoPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/servicoDetalhe`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkInProgressView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/aceitarProposta`; params?: Router.UnknownOutputParams; } | { pathname: `/agendar`; params?: Router.UnknownOutputParams; } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmarContratacao`; params?: Router.UnknownOutputParams; } | { pathname: `/contratante`; params?: Router.UnknownOutputParams; } | { pathname: `/enviarProposta`; params?: Router.UnknownOutputParams; } | { pathname: `/homeContratante`; params?: Router.UnknownOutputParams; } | { pathname: `/homePrestador`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mensagens`; params?: Router.UnknownOutputParams; } | { pathname: `/meusProjetos`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/perfilPrestador`; params?: Router.UnknownOutputParams; } | { pathname: `/postarServico`; params?: Router.UnknownOutputParams; } | { pathname: `/prestador`; params?: Router.UnknownOutputParams; } | { pathname: `/resumoPagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/servicoDetalhe`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorkInProgressView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/aceitarProposta${`?${string}` | `#${string}` | ''}` | `/agendar${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/confirmarContratacao${`?${string}` | `#${string}` | ''}` | `/contratante${`?${string}` | `#${string}` | ''}` | `/enviarProposta${`?${string}` | `#${string}` | ''}` | `/homeContratante${`?${string}` | `#${string}` | ''}` | `/homePrestador${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mensagens${`?${string}` | `#${string}` | ''}` | `/meusProjetos${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/perfilPrestador${`?${string}` | `#${string}` | ''}` | `/postarServico${`?${string}` | `#${string}` | ''}` | `/prestador${`?${string}` | `#${string}` | ''}` | `/resumoPagamento${`?${string}` | `#${string}` | ''}` | `/servicoDetalhe${`?${string}` | `#${string}` | ''}` | `/../components/WorkInProgressView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/aceitarProposta`; params?: Router.UnknownInputParams; } | { pathname: `/agendar`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/confirmarContratacao`; params?: Router.UnknownInputParams; } | { pathname: `/contratante`; params?: Router.UnknownInputParams; } | { pathname: `/enviarProposta`; params?: Router.UnknownInputParams; } | { pathname: `/homeContratante`; params?: Router.UnknownInputParams; } | { pathname: `/homePrestador`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mensagens`; params?: Router.UnknownInputParams; } | { pathname: `/meusProjetos`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/perfilPrestador`; params?: Router.UnknownInputParams; } | { pathname: `/postarServico`; params?: Router.UnknownInputParams; } | { pathname: `/prestador`; params?: Router.UnknownInputParams; } | { pathname: `/resumoPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/servicoDetalhe`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkInProgressView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
